# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Generate Allure Report
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Allure Report 

env:
  PRIMARY_PYTHON_VERSION: '3.10'
  PRIMARY_PLATFORM: 'ubuntu-latest'
  PYTEST_CMD: >-
    python -m pytest tests/
    --junitxml=pytest.xml
    --alluredir=./allure-results

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: github-pages
      cancel-in-progress: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{env.PRIMARY_PYTHON_VERSION}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.PRIMARY_PYTHON_VERSION}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        #pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest and Allure report
      run: |
        ${{env.PYTEST_CMD}}

    - name: Load Allure test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Publish Allure test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        destination_dir: nithyaudhaya.github.io/github-allure-history/${{ github.run_number }}